# Site settings
name: Ana Satostegui
title: Ana's Blog
email: anaisato@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Professional Web Application Designer, Developer, Learner
baseurl: "" # the subpath of your site, e.g. /blog/
url: "aisatos.github.io" # the base hostname & protocol for your site
twitter_username: anisatos
github_username:  aisatos
linkedin_username: anasatostegui

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Your disqus shortname, entering this will enable commenting on posts
disqus: 'satos'

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-64965352-1

permalink: /:title/

paginate: 5

